### ISSUE TITLE
CalibrationData's members are private

### ISSUE THREAD

**Issue by ssquirrel** [asap2Go/calibrationReader#1]
Cool library. In case you did not notice, a2l inside CalibrationData is not accessible from the outside.

 By the way, when do you plan to implement reading characteristics's values from hex file?

**Comment by asap2Go** [comment]
Hey, thanks for the Info!
I just recently had some time to get rid of what I believe are the last bugs in the tokenizer. 
Implementing the reading of the characteristics values are next on the list.
While I am sure that I have time to do it before the end of the year I am not exactly sure if it'll turn out to be november or december.
Most members of calibrationReader are still private as I haven't implemented the API yet and it wasn't necessary for internal testing. I can do that this week so the package becomes accessible for preliminary use.
Some members in the a2l package might also need to become exported in the future in order to implement the reading of characteristic values.

**Comment by asap2Go** [comment]
calibrationData's member are now public.
Half the implementation to read out values from hex is also done.
I hope to be done by end of november.
As far as I know. There are many little pitfalls in this standard.
